import type { Post } from '../types'

// Newest post first
export const posts: Post[] = [
  {
    type: 'photo',
    id: 'p9',
    date: '28. dubna 2026',
    text: 'A jsme tady! 🌊☀️',
    image: '/images/posts/dovolena.png',
    likes: 156,
    comments: 34,
  },
  {
    type: 'text',
    id: 'p8',
    date: '21. dubna 2026',
    text: 'Za týden konečně vyrážíme k moři! Celá rodina po dlouhé době pohromadě 🌴',
    likes: 77,
    comments: 21,
  },
  {
    type: 'photo',
    id: 'p2',
    date: '18. dubna 2026',
    text: 'Buddy si dneska užíval zahradu 🐶 nejlepší parťák ❤️',
    image: '/images/posts/pes.png',
    likes: 89,
    comments: 16,
  },
  {
    type: 'photo',
    id: 'p6',
    date: '12. března 2026',
    text: 'Pohodička doma večer 🎮📺',
    image: '/images/posts/obyvak.png',
    likes: 38,
    comments: 5,
  },
  {
    type: 'photo',
    id: 'p1',
    date: '20. ledna 2026',
    text: 'Tak konečně! Za půl roku jdu na Metallicu 🤘 Nemůžu se dočkat!',
    image: '/images/posts/listek.png',
    likes: 132,
    comments: 27,
  },
  {
    type: 'photo',
    id: 'p7',
    date: '23. listopadu 2025',
    text: 'Dnešní běh 💪 zase jsem začal i skončil doma 😅',
    image: '/images/posts/strava.png',
    likes: 61,
    comments: 13,
  },
  {
    type: 'life-event',
    id: 'p12',
    date: '1. září 2023',
    event: 'Začal nové zaměstnání',
    description: 'Software Engineer ve firmě GoodData, Brno',
  },
  {
    type: 'photo',
    id: 'p4',
    date: '26. října 2019',
    text: 'Konečně 18! 🎉 Díky všem za přání!',
    image: '/images/posts/dort.png',
    likes: 214,
    comments: 64,
  },
  {
    type: 'photo',
    id: 'p5',
    date: '19. května 2019',
    text: 'Trochu uklizeno v pokoji 😄',
    image: '/images/posts/klice.png',
    likes: 45,
    comments: 8,
  },
  {
    type: 'checkin',
    id: 'p10',
    date: '25. března 2018',
    place: 'O2 Arena, Praha',
    text: 'Tady to žije 🔥',
    likes: 49,
    comments: 6,
  },
]